name: Build and push Docker images

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 1 * * 1'

jobs:
  java-minimal:
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: java-minimal
      context: java-minimal
      base_image: base
      java_versions: 11,17,20
    secrets: inherit
  java-maven:
    needs: [java-minimal]
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: java-maven
      context: java-maven
      base_image: java-minimal
      java_versions: 11,17,20
    secrets: inherit
  vscode-maven:
    needs: [java-maven]
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: vscode-maven
      context: vscode
      test: true
      base_image: java-maven
      java_versions: 11,17,20
    secrets: inherit
