name: Build and push Docker images

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 1 * * 1'

jobs:
  java-minimal:
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: java-minimal
      context: java-minimal
      base_image: base
      java_versions: 11,17,20
    secrets: inherit
